services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
