services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - /dev:/dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
